version: '3.8'

services:
  wit-timetable:
    image: wit-timetable
    container_name: wit-timetable
    build:
      context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5000:5000
    security_opt:
      - no-new-privileges:true
    environment:
      - PORT:5000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
